#!/usr/bin/env python3
"""
An autogenerated testfile for python.
"""

import unittest
from unittest.mock import patch
from io import StringIO
import re
import os
import sys
import inspect
from unittest import TextTestRunner
from examiner import tags, ExamTestCase, ExamTestResult
from examiner import import_module, find_path_to_assignment


FILE_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_PATH = find_path_to_assignment(FILE_DIR)

if REPO_PATH not in sys.path:
    sys.path.insert(0, REPO_PATH)

# Path to file and basename of the file to import
main = import_module(REPO_PATH, 'main')
marvin2 = import_module(REPO_PATH, 'marvin2')


class Test2Marvin2NewMenus(ExamTestCase):
    """
    Each assignment has 1 testcase with multiple asserts.
    The different asserts https://docs.python.org/3.6/library/unittest.html#test-cases
    """

    @classmethod
    def setUpClass(cls):
        """
        To find all relative files that are read or written to.
        """
        os.chdir(REPO_PATH)


    def check_print_contain(self, inp, correct, func):
        """
        One function for testing print input functions.
        """
        with patch("builtins.input", side_effect=inp):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                func()
                str_data = fake_out.getvalue()
                for val in correct:
                    self.assertIn(val, str_data)



    @tags("9", "marvin2")
    def test_create_ssn_func(self):
        """
        Testar att anropa menyval 9 via main funktionen i main.py.
        Använder följande som input:
        {arguments}
        Förväntar att ett giltigt personnummer har rätt struktur:
        {correct}
        Det har inte strukturen, ÅÅMMDD-NNNN:
        {student}
        """
        self.norepr = True
        birthdate = "030123"
        self._multi_arguments = ["9", birthdate, "", "q"]

        with patch("builtins.input", side_effect=self._multi_arguments):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()

        pattern = r"[^\d](030123-\d{4})[^\d]"
        self.fail_msg.student_answer = str_data
        self.fail_msg.correct_answer = repr(f"{birthdate}-NNNN")
        if re.search(pattern, str_data) is None:
            raise AssertionError
        ssn = re.search(pattern, str_data)[1]

        self._multi_arguments = ["7", ssn, "", "q"]
        with patch("builtins.input", side_effect=self._multi_arguments):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()
            self.assertIn("Valid", str_data, msg=[
                "Använder funktionen 'validate_ssn()' för att validera det genererade personnummret:",
                "Personnummret var inte giltigt:"
            ])



    @tags("10", "marvin2")
    def test_get_acronym_menu(self):
        """
        Testar att anropa menyval 10 via main funktionen i main.py.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskrift:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = ["10", "BRöderna Ivarsson Osby", "", "q"]
        self.check_print_contain(
            self._multi_arguments,
            ["BRIO"],
            main.main
        )



    @tags("11", "marvin2")
    def test_randomize_string_menu(self):
        """
        Testar att anropa menyval 11 via main funktionen i main.py.
        Använder följande som input:
        {arguments}
        Förväntar att följande sträng finns med i utskrift fast med bokstäverna i annan ordning:
        {correct}
        Fick följande:
        {student}
        """
        string = "Borde inte bli samma igen"
        self._multi_arguments = ["11", string, "", "q"]

        with patch("builtins.input", side_effect=self._multi_arguments):
            with patch("sys.stdout", new=StringIO()) as fake_out:
                main.main()
                str_data = fake_out.getvalue()

        length = len(string)
        pattern = fr"{string} --> ([{string}]{{{length}}})"

        self.fail_msg.student_answer = str_data
        self.fail_msg.correct_answer = repr(f"{string} --> <en slumpad ordning>")


        try:
            rnd_str = re.search(pattern, str_data)[1]
        except TypeError:
            raise AssertionError
        if string == rnd_str or sorted(string) != sorted(rnd_str):
            raise AssertionError



    @tags("12", "marvin2")
    def test_find_all_indexes_menu(self):
        """
        Testar att anropa menyval 12 i main.py.
        Använder följande som input:
        {arguments}
        Förväntar att följande finns med i utskriften:
        {correct}
        Fick följande:
        {student}
        """
        self.norepr = True
        self._multi_arguments = [
            "12",
            "There's unlimited juice? This party is gonna be off the hook. Oh, I'm sorry, I forgot... your wife is dead!.",
            "is",
            "",
            "q"
        ]

        self.check_print_contain(
            self._multi_arguments,
            ["27,36,99"],
            main.main
        )



if __name__ == '__main__':
    runner = TextTestRunner(resultclass=ExamTestResult, verbosity=2)
    unittest.main(testRunner=runner, exit=False)
